name: 'application build'
run-name: 'application build'
env:
  CODE_PATH: application/src/az_function
on:
  push:
    paths:
      - application/src/az_function/**
    branches:
      - main
  pull_request:
    paths:
      - application/src/az_function/**
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.CODE_PATH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: dependencies
        run: dotnet restore
      - name: build
        run: dotnet build --configuration Release --no-restore --output ./output
      - name: test
        run: dotnet test --no-restore --verbosity normal
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ env.CODE_PATH }}/output/*

      # - name: pack
      #   run: dotnet pack --configuration Release
      # - name: artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: package
      #     path: ${{ env.CODE_PATH }}/bin/Release/*.nupkg
