name: application build
run-name: application build
env:
  CODE_PATH: application/src/az_function
on:
  push:
    paths:
      - application/src/az_function/**
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ${{ env.CODE_PATH }}
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: dependencies
        run: dotnet restore
      - name: build
        run: dotnet build --configuration Release --no-restore
      - name: test
        run: dotnet test --no-restore --verbosity normal
      - name: pack
        run: dotnet pack --configuration Release
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/Release/*.nupkg
