# Reusable shared workflow to deploy Azure Function build artifact to Azure Function App services based on config.json.

name: 'az_function_deploy'
run-name: 'az_function_deploy ${{ inputs.code_path }}'
on:
  workflow_call:
    inputs:
      code_path:
        description: 'Repository relative path to Azure Function code without starting slash'
        type: string
        required: true
      artifact_name:
        description: "Name of build artifact"
        type: string
        default: azure_function
      environment_type:
        description: "Deployment environment type"
        type: string
        required: true
      environment:
        description: "Deployment environment name"
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  config:
    name: Config ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.code_path }}
    outputs:
      az_tenant_id: ${{ steps.config.outputs.az_tenant_id }}
      az_subscription_id: ${{ steps.config.outputs.az_subscription_id }}
      function_app_names: ${{ steps.config.outputs.function_app_names }}
    steps:
      - uses: actions/checkout@v3
      - name: Config
        id: config
        env:
          CONFIG_FILE: .workflows/config.json
        run: |
          ls $CONFIG_FILE
          echo "az_tenant_id=$(cat $CONFIG_FILE | jq -r '.environment_types."${{ inputs.environment_type }}".az_tenant_id')" >> $GITHUB_OUTPUT
          echo "az_subscription_id=$(cat $CONFIG_FILE | jq -r '.environment_types."${{ inputs.environment_type }}".environments."${{  inputs.environment }}".az_subscription_id')" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "function_app_names<<$EOF" >> $GITHUB_OUTPUT
          cat $CONFIG_FILE | jq -r '.environment_types."${{ inputs.environment_type }}".environments."${{  inputs.environment }}".function_app_names' >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Debug config 
        env:
          CONFIG_FILE: .workflows/config.json
        run: |
          echo config_file=$CONFIG_FILE
          cat $CONFIG_FILE
          echo az_tenant_id=${{ steps.config.outputs.az_tenant_id }}
          echo az_subscription_id=${{ steps.config.outputs.az_subscription_id }}
          echo function_app_names="${{ steps.config.outputs.function_app_names }}"

  deploy:
    name: Deploy ${{ inputs.environment }} (${{ matrix.function_app_name }}, ${{ needs.config.outputs.az_subscription_id }})
    if: needs.config.outputs.function_app_names != 'null'
    runs-on: ubuntu-latest
    needs: config
    strategy:
      matrix:
        function_app_name: ${{ fromJSON(needs.config.outputs.function_app_names) }}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: Run az login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZ_CLIENT_ID }}
          tenant-id: ${{ needs.config.outputs.az_tenant_id }}
          subscription-id: ${{ needs.config.outputs.az_subscription_id }}
      - name: Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ matrix.function_app_name }}
          package: .
