name: gitleaks
on:
  pull_request:
    branches:
      - main
jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: |
          curl --location -O https://github.com/gitleaks/gitleaks/releases/download/v8.17.0/gitleaks_8.17.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.17.0_linux_x64.tar.gz
          cp gitleaks /usr/local/bin/
      - uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ github.head_ref }}
          fetch-depth: 0
      - name: Git fetch
        run: |
          git fetch --no-tags origin +refs/heads/main
      - name: Detect leaked secrets
        run: |
          gitleaks detect -v --log-opts origin/main..origin/${{ github.head_ref }}
