name: 'infrastructure deploy'
run-name: 'infrastructure deploy'
on:
  workflow_dispatch:
  push:
    paths:
      - 'infrastructure/src/**'
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/infrastructure_deploy.yml
    branches:
      - main

jobs:
  deploy:
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: artifact
        uses: dawidd6/action-download-artifact@v2
        # uses: actions/download-artifact@v3
        with:
          workflow: infrastructure_build.yml
          name: terraform-plan
      - name: terraform apply
        run: |
          terraform apply -auto-approve -input=false terraform.tfplan
