name: 'infrastructure build'
run-name: 'infrastructure build'  # check if possible to path that if filtered in triggers
env:
  CODE_PATH: infrastructure/src
on:
  push:
    paths:
      - 'infrastructure/src/**'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: env
        run: |
          env
      - name: terraform init
        working-directory: ${{ env.CODE_PATH }}
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        run: |
          terraform init -backend-config=resource_group_name=${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }} \
            -backend-config=storage_account_name=${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }} \
            -backend-config=container_name=${{ vars.TF_BACKEND_CONTAINER_NAME }}  -backend-config=key=${{ vars.TF_BACKEND_KEY }}
      - name: terraform plan
        working-directory: ${{ env.CODE_PATH }}
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
          TF_VAR_location: ${{ vars.TF_VAR_LOCATION }}
          TF_VAR_name_prefix: ${{ vars.TF_VAR_NAME_PREFIX }}
        run: |
          echo "Run terraform plan"
          terraform plan
