name: 'infrastructure build'
run-name: 'infrastructure build'  # check if possible to path that if filtered in triggers
on:
  push:
    paths:
      - 'infrastructure/src/**'
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: az login
        run: |
          az login --service-principal --username "${{ vars.AZ_CLIENT_ID }}"  --password "${{ secrets.AZ_CLIENT_SECRET }}" --tenant "${{ vars.AZ_TENANT }}"
      - name: az subscription
        run: |
          az account set --subscription ${{ vars.AZ_SUBSCRIPTION_ID }}
      - name: terraform init
        run: |
          terraform init -backend-config=resource_group_name=${{ vars.TF_BACKEND_RESOURCE_GROUP_NAME }} \
            -backend-config=storage_account_name=${{ vars.TF_BACKEND_STORAGE_ACCOUNT_NAME }} \
            -backend-config=container_name=${{ vars.TF_BACKEND_CONTAINER_NAME }}  -backend-config=key=${{ vars.TF_BACKEND_KEY }}
      - name: terraform plan
        run: |
          echo "Run terraform plan"
          terraform plan
