name: parse_config
run-name: parse_config
on:
  workflow_dispatch:
jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.config }}
    steps:
      - uses: actions/checkout@v3
      # value cannot be more than 128KB
      - name: Parse config
        id: config
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "config<<$EOF" >> $GITHUB_OUTPUT
          cat application/src/az_function/.workflows/config.json >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Print config output
        run: |
          echo "${{ steps.config.outputs.config }}"
  print:
    runs-on: ubuntu-latest
    needs: config
    env:
      az_tenant_id: ${{ fromJson(needs.config.outputs.config).environments.pre_prod.az_tenant_id }}
      function_app_names: ${{ toJson(fromJson(needs.config.outputs.config).environments.pre_prod.function_app_names) }}
    steps:
      - name: print
        run: |
          echo az_tenant_id=$az_tenant_id
          echo function_app_names=$function_app_names